########################################################################
# EdgeSense AI — Azure Container Apps (Phase 1, cost-optimised)
#
# What this provisions:
#   - Resource group
#   - Azure Container Registry (Basic — cheapest)
#   - Log Analytics workspace (required by the Container Apps env)
#   - Container Apps Environment (Consumption plan, scale-to-zero)
#   - User-assigned identity with AcrPull (managed-identity image pulls,
#     no admin password stored anywhere)
#   - 4 container apps: mosquitto broker, inference (scale 0->1),
#     edge-agent, simulator, and an externally-reachable dashboard
#
# Cost note: the Consumption plan bills per vCPU-second; apps that scale to
# zero cost ~nothing when idle. This keeps you well inside the EUR 200 credit.
# Run `az containerapp env delete` / `terraform destroy` when not demoing.
########################################################################

locals {
  name = var.prefix
}

data "azurerm_client_config" "current" {}

# Phase-1-native broker credential. Always generated by Terraform, never in
# git/tfvars. Phase 3 (enable_phase3 = true) additionally copies this same
# value into Key Vault and switches the container apps to a Key Vault secret
# reference — the password itself doesn't change, so no rotation glitch.
resource "random_password" "broker_agent" {
  length  = 24
  special = false
}

resource "azurerm_resource_group" "this" {
  name     = "${local.name}-rg"
  location = var.location
  tags     = var.tags
}

# --- Container registry ------------------------------------------------
resource "azurerm_container_registry" "this" {
  name                = "${local.name}acr${random_string.suffix.result}"
  resource_group_name = azurerm_resource_group.this.name
  location            = azurerm_resource_group.this.location
  sku                 = "Basic"
  admin_enabled       = false # we pull via managed identity instead
  tags                = var.tags
}

resource "random_string" "suffix" {
  length  = 5
  upper   = false
  special = false
}

# --- Managed identity for ACR pulls ------------------------------------
resource "azurerm_user_assigned_identity" "apps" {
  name                = "${local.name}-apps-id"
  resource_group_name = azurerm_resource_group.this.name
  location            = azurerm_resource_group.this.location
  tags                = var.tags
}

resource "azurerm_role_assignment" "acr_pull" {
  scope                = azurerm_container_registry.this.id
  role_definition_name = "AcrPull"
  principal_id         = azurerm_user_assigned_identity.apps.principal_id
}

# --- Observability backing store for the environment -------------------
resource "azurerm_log_analytics_workspace" "this" {
  name                = "${local.name}-logs"
  resource_group_name = azurerm_resource_group.this.name
  location            = azurerm_resource_group.this.location
  sku                 = "PerGB2018"
  retention_in_days   = 30
  tags                = var.tags
}

# --- Container Apps environment ----------------------------------------
resource "azurerm_container_app_environment" "this" {
  name                       = "${local.name}-env"
  resource_group_name        = azurerm_resource_group.this.name
  location                   = azurerm_resource_group.this.location
  log_analytics_workspace_id = azurerm_log_analytics_workspace.this.id
  tags                       = var.tags
}

# Reusable image path helper
locals {
  registry = azurerm_container_registry.this.login_server
  images = {
    inference = "${local.registry}/edgesense-inference:${var.image_tag}"
    agent     = "${local.registry}/edgesense-agent:${var.image_tag}"
    simulator = "${local.registry}/edgesense-simulator:${var.image_tag}"
    dashboard = "${local.registry}/edgesense-dashboard:${var.image_tag}"
  }

  registry_block = {
    server   = local.registry
    identity = azurerm_user_assigned_identity.apps.id
  }
}

########################################################################
# 1. MQTT broker (single broker for Phase 1 — the agent uses one broker
#    for sensors + events when EDGESENSE_UPLINK_BROKER is unset).
#    Internal TCP ingress on 1883. Uses the stock eclipse-mosquitto image
#    with an anonymous listener written at startup (demo only).
########################################################################
resource "azurerm_container_app" "broker" {
  name                         = "${local.name}-broker"
  resource_group_name          = azurerm_resource_group.this.name
  container_app_environment_id = azurerm_container_app_environment.this.id
  revision_mode                = "Single"
  tags                         = var.tags

  identity {
    type         = "UserAssigned"
    identity_ids = [azurerm_user_assigned_identity.apps.id]
  }

  ingress {
    external_enabled = false
    transport        = "tcp"
    target_port      = 1883
    exposed_port     = 1883
    traffic_weight {
      latest_revision = true
      percentage      = 100
    }
  }

  # Phase 1: plain Terraform-generated secret. Phase 3 (enable_phase3 = true)
  # switches this to a Key Vault reference resolved via managed identity.
  secret {
    name                = "agent-password"
    value               = var.enable_phase3 ? null : random_password.broker_agent.result
    key_vault_secret_id = var.enable_phase3 ? try(azurerm_key_vault_secret.broker_agent_password[0].versionless_id, null) : null
    identity            = var.enable_phase3 ? azurerm_user_assigned_identity.apps.id : null
  }

  template {
    min_replicas = 1
    max_replicas = 1

    container {
      name   = "mosquitto"
      image  = "docker.io/library/eclipse-mosquitto:2"
      cpu    = 0.25
      memory = "0.5Gi"

      env {
        name        = "AGENT_PASSWORD"
        secret_name = "agent-password"
      }

      # allow_anonymous stays true so the simulator/dashboard (no cred
      # support yet) keep working; the agent authenticates. Flip to false
      # once all clients pass credentials.
      # chown: mosquitto_passwd writes the file 600 root:root, but mosquitto
      # drops to the 'mosquitto' user and must be able to read it.
      command = ["/bin/sh", "-c"]
      args = [
        "printf 'listener 1883 0.0.0.0\\nallow_anonymous true\\npassword_file /mosquitto/config/passwd\\n' > /mosquitto/config/mosquitto.conf && mosquitto_passwd -c -b /mosquitto/config/passwd agent \"$AGENT_PASSWORD\" && chown mosquitto: /mosquitto/config/passwd && exec /usr/sbin/mosquitto -c /mosquitto/config/mosquitto.conf"
      ]
    }
  }
}

########################################################################
# 2. Inference sidecar (FastAPI). Internal HTTP ingress, scales to zero.
########################################################################
resource "azurerm_container_app" "inference" {
  name                         = "${local.name}-inference"
  resource_group_name          = azurerm_resource_group.this.name
  container_app_environment_id = azurerm_container_app_environment.this.id
  revision_mode                = "Single"
  tags                         = var.tags

  identity {
    type         = "UserAssigned"
    identity_ids = [azurerm_user_assigned_identity.apps.id]
  }

  registry {
    server   = local.registry_block.server
    identity = local.registry_block.identity
  }

  ingress {
    external_enabled = false
    target_port      = 8800
    transport        = "http"
    traffic_weight {
      latest_revision = true
      percentage      = 100
    }
  }

  template {
    min_replicas = 0 # scale-to-zero: no cost when idle
    max_replicas = 2

    container {
      name   = "inference"
      image  = local.images.inference
      cpu    = 0.5
      memory = "1Gi"
    }

    # Wake the service on inbound HTTP.
    http_scale_rule {
      name                = "http-requests"
      concurrent_requests = 20
    }
  }
}

########################################################################
# 3. Edge agent (Go). No ingress; connects out to broker + inference.
########################################################################
resource "azurerm_container_app" "agent" {
  name                         = "${local.name}-agent"
  resource_group_name          = azurerm_resource_group.this.name
  container_app_environment_id = azurerm_container_app_environment.this.id
  revision_mode                = "Single"
  tags                         = var.tags

  identity {
    type         = "UserAssigned"
    identity_ids = [azurerm_user_assigned_identity.apps.id]
  }

  registry {
    server   = local.registry_block.server
    identity = local.registry_block.identity
  }

  # Phase 1: plain Terraform-generated secret. Phase 3 (enable_phase3 = true)
  # switches this to a Key Vault reference resolved via managed identity.
  secret {
    name                = "broker-password"
    value               = var.enable_phase3 ? null : random_password.broker_agent.result
    key_vault_secret_id = var.enable_phase3 ? try(azurerm_key_vault_secret.broker_agent_password[0].versionless_id, null) : null
    identity            = var.enable_phase3 ? azurerm_user_assigned_identity.apps.id : null
  }

  template {
    min_replicas = 1
    max_replicas = 1

    container {
      name   = "agent"
      image  = local.images.agent
      cpu    = 0.25
      memory = "0.5Gi"

      env {
        name  = "EDGESENSE_BROKER"
        value = "tcp://${azurerm_container_app.broker.name}:1883"
      }
      env {
        name  = "EDGESENSE_BROKER_USERNAME"
        value = "agent"
      }
      env {
        name        = "EDGESENSE_BROKER_PASSWORD"
        secret_name = "broker-password"
      }
      env {
        # Internal HTTP ingress is served over TLS on 443 via the app FQDN.
        name  = "EDGESENSE_INFERENCE_URL"
        value = "https://${azurerm_container_app.inference.ingress[0].fqdn}/score"
      }
      env {
        name  = "EDGESENSE_METRICS_ADDR"
        value = ":8890"
      }
    }
  }
}

########################################################################
# 4. Simulator. No ingress; publishes sensor readings to the broker.
########################################################################
resource "azurerm_container_app" "simulator" {
  name                         = "${local.name}-simulator"
  resource_group_name          = azurerm_resource_group.this.name
  container_app_environment_id = azurerm_container_app_environment.this.id
  revision_mode                = "Single"
  tags                         = var.tags

  identity {
    type         = "UserAssigned"
    identity_ids = [azurerm_user_assigned_identity.apps.id]
  }

  registry {
    server   = local.registry_block.server
    identity = local.registry_block.identity
  }

  template {
    min_replicas = 1
    max_replicas = 1

    container {
      name   = "simulator"
      image  = local.images.simulator
      cpu    = 0.25
      memory = "0.5Gi"

      # simulate.py is configured via CLI args only (image CMD defaults to
      # the compose hostname 'mosquitto', which doesn't resolve here).
      args = ["--broker", azurerm_container_app.broker.name, "--port", "1883", "--machines", "3"]
    }
  }
}

########################################################################
# 5. Streamlit dashboard. Externally reachable (this is your demo URL).
########################################################################
resource "azurerm_container_app" "dashboard" {
  name                         = "${local.name}-dashboard"
  resource_group_name          = azurerm_resource_group.this.name
  container_app_environment_id = azurerm_container_app_environment.this.id
  revision_mode                = "Single"
  tags                         = var.tags

  identity {
    type         = "UserAssigned"
    identity_ids = [azurerm_user_assigned_identity.apps.id]
  }

  registry {
    server   = local.registry_block.server
    identity = local.registry_block.identity
  }

  ingress {
    external_enabled = true
    target_port      = 8501
    transport        = "http"
    traffic_weight {
      latest_revision = true
      percentage      = 100
    }
  }

  template {
    min_replicas = 0
    max_replicas = 1

    container {
      name   = "dashboard"
      image  = local.images.dashboard
      cpu    = 0.5
      memory = "1Gi"

      # app.py reads HOST/PORT separately (not the tcp:// URL form).
      env {
        name  = "EDGESENSE_BROKER_HOST"
        value = azurerm_container_app.broker.name
      }
      env {
        name  = "EDGESENSE_BROKER_PORT"
        value = "1883"
      }
    }
  }
}
