########################################################################
# Phase 3 — Key Vault secrets + Azure Managed Grafana
#
# 1. Broker credentials generated by Terraform, stored ONLY in Key Vault
#    (never in state-adjacent tfvars or the repo), and surfaced to the
#    agent container app via a managed-identity Key Vault reference.
# 2. Azure Managed Grafana for dashboards/alerting.
#
# Cost: Managed Grafana Standard ≈ €8–10/month base. Grafana is the one
# Phase-3 resource worth destroying between demo periods:
#   terraform destroy -target=azurerm_dashboard_grafana.this
########################################################################

# --- Broker credential: copy the Phase-1 password (main.tf) into KV ----
# Reuses random_password.broker_agent from main.tf so the value the broker
# actually authenticates with never changes when this phase switches on.
resource "azurerm_key_vault_access_policy" "deployer" {
  count        = var.enable_phase3 ? 1 : 0
  key_vault_id = azurerm_key_vault.ml[0].id
  tenant_id    = data.azurerm_client_config.current.tenant_id
  object_id    = data.azurerm_client_config.current.object_id

  secret_permissions = ["Get", "List", "Set", "Delete", "Purge"]

  lifecycle {
    precondition {
      condition     = var.enable_phase2_azureml
      error_message = "enable_phase3 requires enable_phase2_azureml = true (Phase 3 reuses the AML Key Vault)."
    }
  }
}

resource "azurerm_key_vault_access_policy" "apps" {
  count        = var.enable_phase3 ? 1 : 0
  key_vault_id = azurerm_key_vault.ml[0].id
  tenant_id    = data.azurerm_client_config.current.tenant_id
  object_id    = azurerm_user_assigned_identity.apps.principal_id

  secret_permissions = ["Get", "List"]
}

resource "azurerm_key_vault_secret" "broker_agent_password" {
  count        = var.enable_phase3 ? 1 : 0
  name         = "broker-agent-password"
  value        = random_password.broker_agent.result
  key_vault_id = azurerm_key_vault.ml[0].id

  depends_on = [azurerm_key_vault_access_policy.deployer]
}

# --- Managed Grafana ---------------------------------------------------
resource "azurerm_dashboard_grafana" "this" {
  count                 = var.enable_phase3 ? 1 : 0
  name                  = "${local.name}-grafana"
  resource_group_name   = azurerm_resource_group.this.name
  location              = azurerm_resource_group.this.location
  grafana_major_version = 11
  sku                   = "Standard"
  tags                  = var.tags

  identity {
    type = "SystemAssigned"
  }
}

# Let Grafana read Azure Monitor / Log Analytics across the RG.
resource "azurerm_role_assignment" "grafana_monitoring_reader" {
  count                = var.enable_phase3 ? 1 : 0
  scope                = azurerm_resource_group.this.id
  role_definition_name = "Monitoring Reader"
  principal_id         = azurerm_dashboard_grafana.this[0].identity[0].principal_id
}

# Make yourself Grafana Admin (portal login via Entra ID).
resource "azurerm_role_assignment" "grafana_admin_me" {
  count                = var.enable_phase3 ? 1 : 0
  scope                = azurerm_dashboard_grafana.this[0].id
  role_definition_name = "Grafana Admin"
  principal_id         = data.azurerm_client_config.current.object_id
}

output "grafana_url" {
  description = "Managed Grafana endpoint (login with your Azure account). Null unless enable_phase3 = true."
  value       = try(azurerm_dashboard_grafana.this[0].endpoint, null)
}

output "key_vault_name" {
  value = try(azurerm_key_vault.ml[0].name, null)
}
