"""Generate uplink-broker auth files (passwd + ACL) — PLATFORM.md §4.2, phase 1.

Writes registry-style *per-device* ACL entries. §4.2 proposes covering the
whole fleet with three `pattern` rules (`pattern write es/%u/sensors/#` …,
username = `<org>/<site>/<machine>`), but mosquitto 2.x pattern substitution
does not work when %u contains slashes — verified against mosquitto 2.1.2,
which denies even a device's own-prefix publish — so this script generates an
explicit block per principal, the fallback §4.2 anticipates. Phase 2 replaces
generated files with the registry driving the dynamic-security plugin.

Principals:
  --device  ORG/SITE/MACHINE:PASSWORD   may publish only under its own prefix,
                                        subscribe only its own control topic
  --gateway ORG/SITE:PASSWORD           edge agent publishing the events of
                                        every machine of one site
                                        (username gw@ORG/SITE)
  --ops     USER:PASSWORD               dashboards / demo tooling: read all
                                        events, publish any control topic

Password hashing uses a local `mosquitto_passwd` when available, otherwise
the eclipse-mosquitto:2 docker image.

Run with no arguments to regenerate the committed demo files (demo-only
credentials, documented in the README):

    python scripts/gen_broker_auth.py
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from pathlib import Path

DEMO_DEVICES = [
    "default/default/machine-01:machine-01-demo-pw",
    "default/default/machine-02:machine-02-demo-pw",
    "default/default/machine-03:machine-03-demo-pw",
    # foreign-tenant device used by scripts/check_acl.py to prove isolation
    "acme/lyon/pump-07:pump-07-demo-pw",
]
DEMO_GATEWAYS = ["default/default:gateway-demo-pw"]
DEMO_OPS = ["ops:ops-demo-pw"]

ACL_HEADER = """\
# GENERATED by scripts/gen_broker_auth.py — do not edit by hand; regenerate instead.
#
# Registry-style per-device ACL entries (PLATFORM.md §4.2, phase 1).
# The doc's single pattern rules:
#     pattern write es/%u/sensors/#
#     pattern write es/%u/events
#     pattern read  es/%u/control
# do NOT work on mosquitto 2.x when the username contains slashes (verified
# on 2.1.2: even a device's own-prefix publish is denied), so every device
# gets an explicit block — the fallback §4.2 anticipates. Phase 2 moves this
# into the registry (dynamic-security plugin).
"""


def split_cred(spec: str, kind: str) -> tuple[str, str]:
    name, sep, password = spec.partition(":")
    if not sep or not name or not password:
        sys.exit(f"bad --{kind} {spec!r}: expected NAME:PASSWORD")
    return name, password


def acl_blocks(devices: list[str], gateways: list[str], ops: list[str]) -> str:
    out = [ACL_HEADER]
    for spec in devices:
        triple, _ = split_cred(spec, "device")
        if triple.count("/") != 2:
            sys.exit(f"bad --device {triple!r}: expected ORG/SITE/MACHINE")
        out.append(f"""\
# device {triple}
user {triple}
topic write es/{triple}/sensors/#
topic write es/{triple}/events
topic read es/{triple}/control
""")
    for spec in gateways:
        pair, _ = split_cred(spec, "gateway")
        if pair.count("/") != 1:
            sys.exit(f"bad --gateway {pair!r}: expected ORG/SITE")
        out.append(f"""\
# site gateway {pair} (edge agent publishing events for the whole site)
user gw@{pair}
topic write es/{pair}/+/events
""")
    for spec in ops:
        name, _ = split_cred(spec, "ops")
        out.append(f"""\
# ops {name} (dashboards, demo tooling)
user {name}
topic read es/+/+/+/events
topic write es/+/+/+/control
""")
    return "\n".join(out)


def write_passwd(creds: list[tuple[str, str]], out_dir: Path) -> None:
    passwd = out_dir / "passwd"
    if shutil.which("mosquitto_passwd"):
        passwd.write_text("")
        for user, pw in creds:
            subprocess.run(["mosquitto_passwd", "-b", str(passwd), user, pw], check=True)
        return
    creds_file = out_dir / "creds.tmp"
    creds_file.write_text("".join(f"{u}:{p}\n" for u, p in creds),
                          encoding="utf-8", newline="\n")
    try:
        script = ('rm -f /out/passwd && touch /out/passwd && '
                  'while IFS=: read -r u p; do mosquitto_passwd -b /out/passwd "$u" "$p" '
                  '|| exit 1; done < /out/creds.tmp && chmod 644 /out/passwd')
        subprocess.run(["docker", "run", "--rm", "-v", f"{out_dir.resolve()}:/out",
                        "eclipse-mosquitto:2", "sh", "-c", script], check=True)
    finally:
        creds_file.unlink()


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", default="deploy/secure", help="output directory")
    ap.add_argument("--device", action="append", default=[],
                    metavar="ORG/SITE/MACHINE:PASSWORD")
    ap.add_argument("--gateway", action="append", default=[], metavar="ORG/SITE:PASSWORD")
    ap.add_argument("--ops", action="append", default=[], metavar="USER:PASSWORD")
    args = ap.parse_args()

    if not (args.device or args.gateway or args.ops):
        args.device, args.gateway, args.ops = DEMO_DEVICES, DEMO_GATEWAYS, DEMO_OPS
        print("no principals given — generating the demo set (demo-only credentials!)")

    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)

    (out_dir / "acl").write_text(acl_blocks(args.device, args.gateway, args.ops),
                                 encoding="utf-8", newline="\n")

    creds = [split_cred(s, "device") for s in args.device]
    creds += [(f"gw@{split_cred(s, 'gateway')[0]}", split_cred(s, "gateway")[1])
              for s in args.gateway]
    creds += [split_cred(s, "ops") for s in args.ops]
    write_passwd(creds, out_dir)

    print(f"wrote {out_dir / 'acl'} and {out_dir / 'passwd'} "
          f"({len(creds)} principal(s))")
    return 0


if __name__ == "__main__":
    sys.exit(main())
